import {chromium,expect} from '@playwright/test';
import {stroke,dot,move,tool,state,saved} from './helpers.js';
const browser=await chromium.launch({channel:'chrome'});
const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:'+(process.env.APP_PORT||4174));await page.waitForSelector('body[data-ready="true"]');
await page.screenshot({path:'tests/artifacts/v2/01-blank.png'});
await page.locator('#document-name').fill('Shape study');await page.locator('#document-name').press('Enter');
await page.keyboard.press('r');await stroke(page,70,110,220,110);
await tool(page,'triangle');await page.keyboard.press('b');await stroke(page,300,100,370,170);
await tool(page,'square');await page.keyboard.press('y');await stroke(page,90,230,205,260);
await tool(page,'diamond');await page.keyboard.press('g');await dot(page,340,260);
await tool(page,'chisel');await page.keyboard.press('p');await stroke(page,80,370,210,340);
await tool(page,'star');await page.keyboard.press('m');await stroke(page,290,365,410,365);
await tool(page,'pen');await page.keyboard.press('r');await move(page,380,445);await saved(page);
await page.screenshot({path:'tests/artifacts/v2/02-shape-brushes.png'});
const old=(await state(page)).id;await page.locator('#new-button').click();await expect.poll(async()=>(await state(page)).id).not.toBe(old);
await page.keyboard.press('b');await stroke(page,70,170,430,170);await page.keyboard.press('r');await stroke(page,250,80,250,350);
await page.locator('#gallery-button').click();await expect(page.locator('#gallery-dialog')).toBeVisible();await page.screenshot({path:'tests/artifacts/v2/03-gallery.png'});
await page.keyboard.press('Escape');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/artifacts/v2/04-mobile-100-percent.png'});
console.log(JSON.stringify({chrome:browser.version(),screenshots:4,errors}));await browser.close();
if(errors.length)process.exitCode=1;
